app/dashboard/project/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    # ex: /dashboard/
    path('', views.index, name='index'),
    # ex: /dashboard/23/edit
    path('add', views.add, name='add'),
    # ex: /dashboard/23/
    path('<int:pk>', views.detail, name='detail'),
    # ex: /dashboard/23/edit
    path('<int:pk>/edit', views.edit, name='edit'),
    # ex: /dashboard/23/remove
    path('<int:pk>/remove', views.remove, name='remove'),
    # ex: /dashboard/23/change_version/
    path('<int:pk>/change_version', views.change_version, name='change_version'),
    # ex: /dashboard/23/force_update/
    path('<int:pk>/force_update', views.force_update, name='force_update'),
    # ex: /dashboard/new_version
    path('new_version/<str:version>', views.new_version, name='new_version'),
    # ex: /dashboard/login
    path('login/', views.login_view, name='login'),
    # ex: /dashboard/logout
    path('logout/', views.log_out, name='logout'),
    # ex: /dashboard/register
    path('register/', views.register_view, name='register'),
]

app/dashboard/project/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('dashboard/', include('dashboard.urls')),
    path('', RedirectView.as_view(pattern_name='dashboard:index')),
    path('admin/', admin.site.urls),
]

app/dashboard/project/dashboard/models.py
from django.db import models
from django.core.validators import validate_ipv46_address

class Device(models.Model):
    name = models.CharField('name', max_length=100)
    ip = models.GenericIPAddressField('ip', validators=[validate_ipv46_address])
    date_added = models.DateTimeField('date added')
    last_check = models.DateTimeField('last check', null=True, blank=True)
    last_status = models.CharField('last status', max_length=64, blank=True)
    image = models.CharField('image', max_length=100, blank=True)
    tag = models.CharField('tag', max_length=100, blank=True)
    token = models.CharField('token', max_length=50, blank=False, null=False)

    def __str__(self):
        return self.name

    def get_last_check(self):
        if self.last_check is None:
            return "Never"
        else:
            return self.last_check

    def get_last_status(self):
        if self.last_status != "":
            return f"{self.last_status}"
        else:
            return "Unknown"

    def get_image(self):
        if self.image != "":
            return f"{self.image}"
        else:
            return "Unknown"
    
    def get_tag(self):
        if self.tag != "":
            return f"{self.tag}"
        else:
            return "Unknown"

    def get_image_name(self):
        if self.image != "" and self.tag != "":
            return f"{self.image}:{self.tag}"
        else:
            return "Unknown"

app/dashboard/project/dashboard/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.core.validators import validate_ipv46_address
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout, get_user_model

import json

from .models import Device
from .versions import get_versions

import requests

def login_view(request):
    User = get_user_model()
    users = User.objects.all()
    if not users:
        return redirect(reverse('dashboard:register'))

    if request.user.is_authenticated:
        return redirect(reverse('dashboard:index'))

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        next_url = request.POST['next']
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect(reverse('dashboard:index'))
        else:
            messages.error(request, 'Wrong username and/or password', extra_tags='danger')
            return redirect(f"/dashboard/login?next={next_url}")

    return render(request, 'dashboard/login.html')

def register_view(request):
    User = get_user_model()
    users = User.objects.all()
    if not users:

        if request.method == 'POST':
            # Proceed to add the user
            username = request.POST['username']
            email = request.POST['email']
            password = request.POST['password']
            password2 = request.POST['reenter-password']

            if password != password2:
                messages.error(request, 'The passwords must match', extra_tags='danger')
                return render(request, 'dashboard/register.html')
            
            user = User.objects.create_user(username, email, password)

            messages.success(request, f'User {user.username} registered')
            return redirect(reverse("dashboard:index"))
    else:
        return redirect(reverse("dashboard:index"))

    return render(request, 'dashboard/register.html')

@login_required
def log_out(request):
    logout(request)
    messages.success(request, 'Goodbye!')
    return redirect(reverse('dashboard:index'))

@login_required
def index(request):

    devices = Device.objects.all()
    context = {
        'devices' : devices
    }
    return render(request, 'dashboard/index.html', context)

@login_required
def detail(request, pk):
    device = get_object_or_404(Device, pk=pk)
    try:
        reload = request.GET['refresh']
        if reload == 'true':
            try:
                status = requests.get(f"http://{device.ip}:1221/status",
                                      headers={'Authorization' : f"Bearer {device.token}"},
                                      timeout=15)
                # Raise for status, in case a 401 happen
                status.raise_for_status()
                image = requests.get(f"http://{device.ip}:1221/image",
                                     headers={'Authorization' : f"Bearer {device.token}"},
                                     timeout=15)
                tag = requests.get(f"http://{device.ip}:1221/tag",
                                   headers={'Authorization' : f"Bearer {device.token}"},
                                   timeout=15)
                device.last_check = timezone.now()
                device.last_status = status.json()['status']
                device.image = image.json()['image']
                device.tag = tag.json()['tag']
                device.save()
                messages.success(request, 'The device information was updated successfully')
            except requests.exceptions.Timeout:
                messages.error(request, 'The device couldn\'t be reached: timeout', extra_tags='danger')
            except requests.exceptions.HTTPError as e:
                if status.status_code == 401:
                    messages.error(request, 'Wrong token for device', extra_tags='danger')
                else:
                    messages.error(request, f"HTTP error {status.status_code}", extra_tags='danger')
            except requests.exceptions.RequestException as e:
                messages.error(request, str(e), extra_tags='danger')
            except:
                messages.error(request, 'Unknown error', extra_tags='danger')
                raise
            finally:
                return redirect(reverse('dashboard:detail', args=(pk,)))
    except:
        pass

    return render(request, 'dashboard/detail.html', { 'device' : device })

@login_required
def add(request):

    # If the request is POST, add the devices
    if request.method == 'POST':
        try:
            name = request.POST['name']
            ip = request.POST['ip']
            token = request.POST['token']

            new_device = Device(name=name,
                                ip=ip,
                                token=token,
                                date_added=timezone.now())
            
            new_device.full_clean()
            new_device.save()
            return redirect(reverse('dashboard:detail', args=(new_device.id, )))

        except ValidationError as e:
            for error in e:
                messages.error(request, f"{error[0]}: {error[1][0]}", extra_tags='danger')

    return render(request, 'dashboard/add.html')

@login_required
def edit(request, pk):
    device = get_object_or_404(Device, pk=pk)
    
    # If the request is POST, is the submit of th edit
    if request.method == 'POST':
        try:
            new_name = request.POST['name']
            validate_ipv46_address(request.POST['ip'])
            new_ip = request.POST['ip']
            token = request.POST['token']

            device.name = new_name
            device.ip = new_ip
            device.token = token
            device.save()

            return redirect(reverse('dashboard:detail', args=(pk, )))

        except ValidationError as e:
            messages.error(request, e.message, extra_tags='danger')
        except:
            messages.error(request, 'Please check the values', extra_tags='danger')

    return render(request, 'dashboard/edit.html', { 'device' : device })

@login_required
def remove(request, pk):
    device = get_object_or_404(Device, pk=pk)
    name = device.name
    if request.method == 'POST':
        device.delete()
        messages.success(request, f"Device '{name}' removed")
        return redirect(reverse('dashboard:index'))
    else:
        return redirect(reverse('dashboard:detail', args=(pk,)))


@login_required
def change_version(request, pk):
    device = get_object_or_404(Device, pk=pk)

    if request.method == 'POST':
        try:
            new_tag = request.POST['new_version']

            requests.post(f"http://{device.ip}:1221/tag",
                          json={'tag' : new_tag},
                          headers={'Authorization' : f"Bearer {device.token}"},
                          timeout=15)

            messages.success(request, f"The new version was sent to {device.name}")
            return redirect(f"/dashboard/{pk}?refresh=true")
        except KeyError:
            messages.error(request, 'You must select a tag', extra_tags='danger')
        except:
            messages.error(request, 'The device couldn\t be reached', extra_tags='danger')

    # Get the available version
    versions = get_versions()
    return render(request, 'dashboard/change_version.html', { 'device' : device, 'versions' : versions })

@login_required
def force_update(request, pk):
    device = get_object_or_404(Device, pk=pk)

    if request.method == 'POST':
        try:
            r = requests.post(f"http://{device.ip}:1221/force_update",
                          headers={'Authorization' : f"Bearer {device.token}"},
                          timeout=15)
            r.raise_for_status()
            
            messages.success(request, f"The update was sent to {device.name}")
        except requests.exceptions.HTTPError:
            if r.status_code == 401:
                messages.error(request, 'Wrong token for device', extra_tags='danger')
            else:
                messages.error(request, f"HTTP error {r.status_code}", extra_tags='danger')
        except:
            messages.error(request, 'The device couldn\t be reached', extra_tags='danger')

    return redirect(reverse('dashboard:detail', args=(pk,)))
    
# If there is a new version, update all the corresponding devices
def new_version(request, version):
    if request.method == 'GET':
        try:
            # Get all devices with that version
            devices = Device.objects.filter(tag=version)

            for device in devices:
                try:
                    r = requests.post(f"http://{device.ip}:1221/force_update",
                                headers={'Authorization' : f"Bearer {device.token}"},
                                timeout=15)
                    r.raise_for_status()
                    
                    messages.success(request, f"The update was sent to {device.name}")
                except requests.exceptions.HTTPError:
                    if r.status_code == 401:
                        messages.error(request, 'Wrong token for device', extra_tags='danger')
                    else:
                        messages.error(request, f"HTTP error {r.status_code}", extra_tags='danger')
                except:
                    messages.error(request, 'The device couldn\t be reached', extra_tags='danger')
        except json.JSONDecodeError:
            messages.error(request, 'Malformed request', extra_tags='danger')
        except KeyError:

app/dashboard/project/dashboard/templates/dashboard/add.html
{% extends "dashboard/base.html" %}

{% block content %}

<div class="container">

    <ul class="nav d-flex justify-content-between align-items-center">
        <li class="nav-item">
            <h1 class="display-4 my-4">Add new device</h1>
        </li>
    </ul>

    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif%}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <form action="{% url 'dashboard:add' %}" method="post">
    {% csrf_token %}
    <div class="form-group row">
        <label for="name" class="col-sm-1 col-form-label">Name</label>
        <input type="text" name="name" value="" class="col-sm-11">
    </div>
    <div class="form-group row">
        <label for="ip" class="col-sm-1 col-form-label">IP</label>
        <input type="text" name="ip" value="" class="col-sm-11">
    </div>
    <div class="form-group row">
        <label for="token" class="col-sm-1 col-form-label">Token</label>
        <input type="text" name="token" value="" class="col-sm-11">
    </div>

    <div class="row">
        <a href="{% url 'dashboard:index' %}" class="btn btn-light col-sm-6">Cancel</a>
        <button type="submit" class="btn btn-primary col-sm-6">Save</button>
    </div>
    </form>
</div>

{% endblock %}

app/dashboard/project/dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CI/CD Dashboard</title>

    <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
    crossorigin="anonymous">
    

</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

  <a class="navbar-brand " href="{% url 'dashboard:index' %}">Dashboard</a>
  <ul class="navbar-nav mr-auto"></ul>
  


      {% if request.user.is_authenticated %}
      <form class="form-inline my-lg-0" action="{% url 'dashboard:logout' %}" method="post">
      {% csrf_token %}
        <label class="btn btn-grey" >{{ request.user }}</label>
        <button class="btn btn-grey my-sm-0" type="submit">Logout</button>
      </form>
      {% endif %}
</nav>

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script> 
    <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script> 

</body>
</html>

app/dashboard/project/dashboard/templates/dashboard/change_version.html
{% extends "dashboard/base.html" %}

{% block content %}

<div class="container">

    <ul class="nav d-flex justify-content-between align-items-center">
        <li class="nav-item">
            <h1 class="display-4 my-4">Change version for: {{ device.name }}</h1>
        </li>
    </ul>

    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif%}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    
    <form action="{% url 'dashboard:change_version' device.pk %}" method="post">

        <div class="form-group form-row align-items-center">
        {% csrf_token %}
        
        <div class="col-auto">
            <label>Select new version</label>
        </div>

        <div class="col-auto">
            <select class="custom-select" name="new_version">
                {% for version in versions %}
                    <option value="{{version}}">{{ version }}</option>
                {% endfor %}
            </select>
        </div>

        </div>
        
        <div class="form-group">
        <input class="btn btn-primary" type="submit" value="Change version">
        </div>

    </form>
    </div>

{% endblock %}

app/dashboard/project/dashboard/templates/dashboard/detail.html
{% extends "dashboard/base.html" %}

{% block content %}

<div class="container">

    <ul class="nav d-flex justify-content-between align-items-center my-4">
        <li class="nav-item">
            <h1 class="display-4">Device: {{ device.name }}</h1>
        </li>
        <li class="nav-item">
            <ul class="nav">
                <li class="nav-item mr-1 mb-1">
                    <a class="btn btn-primary" href="{% url 'dashboard:detail' device.id %}?refresh=true" role="button">Check</a>
                </li>
                <li class="nav-item mr-1 mb-1">
                    <a class="btn btn-info" href="{% url 'dashboard:change_version' device.id %}" role="button">Change version</a>
                </li>
                <li class="nav-item mr-1 mb-1">
                    <form class="form-inline  my-lg-0" action="{% url 'dashboard:force_update' device.id %}" method="post">
                    {% csrf_token %}
                        <button class="btn btn-info  my-sm-0" type="submit">Force update</button>
                    </form>
                </li>
                <li class="nav-item mr-1  mb-1">
                    <a class="btn btn-light" href="{% url 'dashboard:edit' device.id %}" role="button">Edit</a>
                </li>
                <li class="nav-item mr-1 mb-1">
                    <form class="form-inline  my-lg-0" action="{% url 'dashboard:remove' device.id %}" method="post">
                    {% csrf_token %}
                        <button class="btn btn-danger  my-sm-0" type="submit">Remove</button>
                    </form>
                </li>
            </ul>
        </li>
    </ul>

    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif%}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="table-responsive">
        <table class="table table-bordered">
        <tbody>
            <tr><th scope="row" width="15%">Name</th><td>{{ device.name }}</td></tr>
            <tr><th scope="row" width="15%">IP</th><td>{{ device.ip }}</td></tr>
            <tr><th scope="row" width="15%">Token</th><td>{{ device.token }}</td></tr>
            <tr><th scope="row" width="15%">Added</th><td>{{ device.date_added }}</td></tr>
            <tr><th scope="row" width="15%">Last check</th><td>{{ device.get_last_check }}</td></tr>
            <tr><th scope="row" width="15%">Last status</th><td>{{ device.get_last_status }}</td></tr>
            <tr><th scope="row" width="15%">Image</th><td>{{ device.get_image }}</td></tr>
            <tr><th scope="row" width="15%">Tag</th><td>{{ device.get_tag }}</td></tr>
        </tbody>
        </table>
    </div>


    {% comment %} Actions {% endcomment %}
</div>

{% endblock %}

app/dashboard/project/dashboard/templates/dashboard/edit.html
{% extends "dashboard/base.html" %}

{% block content %}

<div class="container">

    <ul class="nav d-flex justify-content-between align-items-center">
        <li class="nav-item">
            <h1 class="display-4 my-4">Edit: {{ device.name }}</h1>
        </li>
    </ul>

    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif%}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <form action="{% url 'dashboard:edit' device.pk %}" method="post">
    {% csrf_token %}
    <div class="form-group row">
        <label for="name" class="col-sm-1 col-form-label">Name</label>
        <input type="text" name="name" value="{{device.name}}" class="col-sm-11">
    </div>
    <div class="form-group row">
        <label for="ip" class="col-sm-1 col-form-label">IP</label>
        <input type="text" name="ip" value="{{device.ip}}" class="col-sm-11">
    </div>
    <div class="form-group row">
        <label for="token" class="col-sm-1 col-form-label">Token</label>
        <input type="text" name="token" value="{{device.token}}" class="col-sm-11">
    </div>

    <div class="row">
        <a href="{% url 'dashboard:detail' device.pk %}" class="btn btn-light col-sm-6">Cancel</a>
        <button type="submit" class="btn btn-primary col-sm-6">Save</button>
    </div>
    </form>
</div>

{% endblock %}

app/dashboard/project/dashboard/templates/dashboard/index.html
{% extends "dashboard/base.html" %}

{% block content %}

<div class="container">
    <ul class="nav d-flex justify-content-between align-items-center my-4">
        <li class="nav-item">
            <h1 class="display-4">Devices</h1>
        </li>
        <li class="nav-item">
            <ul class="nav">
                <li class="nav-item mr-1">
                    <a class="btn btn-primary" href="{% url 'dashboard:add' %}" role="button">Add new device</a>
                </li>
            </ul>
        </li>
    </ul>

    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif%}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">IP</th>
            <th scope="col">Last check</th>
            <th scope="col">Last status</th>
            <th scope="col">Image</th>
        </tr>
    </thead>
    <tbody>
        {% for device in devices %}
        <tr>
            <th scope="row">
                <a href="{% url 'dashboard:detail' device.id %}">{{ device.name }}
            </th>
            <td>{{ device.ip }}</td>
            <td>{{ device.get_last_check}}</td>
            <td>{{ device.get_last_status }}</td>
            <td>{{ device.get_image_name }}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
</div>

{% endblock %}

app/dashboard/project/dashboard/templates/dashboard/login.html
{% extends "dashboard/base.html" %}

{% block content %}

<div class="container">


    <h1 class="text-center my-5">Login</h1>

    <div class="row justify-content-center">

    <div class="col-sm-3 text-center ">
        <form action="{% url 'dashboard:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input class="form-control" type="text" id="username" name="username" placeholder="Username">
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input class="form-control" type="password" id="password" name="password">
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary col-sm-12">Login</button>
        </div>

        <input type="hidden" name="next" value="{{ request.GET.next }}">
        </form>

        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif%}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

    </div>
    
    </div>
</div>

{% endblock %}

app/dashboard/project/dashboard/templates/dashboard/register.html
{% extends "dashboard/base.html" %}

{% block content %}

<div class="container">

    <h1 class="text-center my-5">Register</h1>

    <div class="row justify-content-center">

    <div class="col-sm-3 text-center ">
        <form action="{% url 'dashboard:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input class="form-control" type="text" id="username" name="username" placeholder="Username">
        </div>

        <div class="form-group">
            <label for="email">Email</label>
            <input class="form-control" type="email" id="email" name="email" placeholder="Email">
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input class="form-control" type="password" id="password" name="password">
        </div>

        <div class="form-group">
            <label for="password">Re enter password</label>
            <input class="form-control" type="password" id="reenter-password" name="reenter-password">
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary col-sm-12">Login</button>
        </div>

        <input type="hidden" name="next" value="{{ request.GET.next }}">
        </form>

        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif%}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

    </div>
    
    </div>
</div>

{% endblock %}